# =====================================================
#  ===  状态栏 / 主题  ===
# =====================================================

# 切换主题：修改下方文件名即可
#   tmuxline/ 下提供了 sonokai、gruvbox、everforest 等多套配色
source "${TMUX_CONF_PATH}/tmuxline/sonokai-atlantis.tmux.conf"
