# =====================================================
#  ===  状态栏 / 主题  ===
# =====================================================

# 状态栏主题：唯一主题文件（其他 tmuxline 主题已删除，避免宽度未固定问题）
source "${TMUX_CONF_PATH}/tmuxline/sonokai-atlantis.tmux.conf"
